### ISSUE TITLE
Strip release executable?

### ISSUE THREAD

**Issue by charlesnicholson** [facebook/buck2#133]
Hi everyone- I'm starting to play around with buck2 and it looks very interesting!

I noticed that the release build (`cargo build -r`) clocks in at 75MB on my M1 MBP. But, `strip` knocks a solid 23MB off of it! I'm guessing that the buck2 executable isn't meant to be dynamically linked _against_, so maybe it's safe to add a release post-build step that runs `strip`?

<img width="497" alt="Screenshot 2023-04-09 at 10 07 29 AM" src="https://user-images.githubusercontent.com/3010295/230777659-cf72dd2f-7d1b-431c-a14c-61b5719edd89.png">

Might be a free win?

Additionally, though, have you done any size auditing? 52MB is still pretty massive for a natively-compiled executable. I wonder if there are more wins lurking in the map file...

**Comment by stepancheg** [comment]
Unstripped binaries produce better stack traces (when panicking or when using normal anyhow errors with `RUST_BACKTRACE=1`). This is not obvious improvement.

**Comment by charlesnicholson** [comment]
Do you expect every user of buck2 to require stack trace functionality? It's not uncommon to ship fully-stripped binaries, and then when investigating issues, attempt to reproduce them on a more instrumented version of the software.

This is a 30% binary size reduction- if you have 1MM buck2 users each downloading it only once, you've saved 1,000,000 * 23MB == 23TB of global internet traffic, and that's not even considering an army of CI robots that will likely download it from somewhere many times per day. If the hope is that 99+% of them won't experience buck2 crashes, that seems like a huge win :)

**Comment by ndmitchell** [comment]
I'd love to think that Buck2 gets to 1MM, but alas, we are probably a way off for now! At the moment we're definitely keen to get proper stack traces, as that ensures that if/when something goes wrong there isn't a need to try reproducing it first.

For our internal builds we use `--strip-debug` and `-S` on Linux/Mac, which strips most debug info (you can't debug into it), but keeps enough for good stack traces. From memory, I think that saved 90% of the space compared to full stripping. That's probably a good point to aim for. CC @themarwhal (see `deploy/buck2_upload.py` for what we do internally).

**Comment by stevefan1999-personal** [comment]
My two cents -- maybe add these to Cargo.toml:

```toml
[profile.release]
incremental = true
lto = "thin"
strip = "debuginfo"

[profile.min-size-release]
inherits = "release"
codegen-units = 1
lto = "fat"
opt-level = "s"

[profile.release-strip]
inherits = "release"
strip = "symbols"

[profile.min-size-release-strip]
inherits = "min-size-release"
strip = "symbols"
```
