### ISSUE TITLE
Inconsistent handling of cargo_env in `buildscript_run`

### ISSUE THREAD

**Issue by yxdai-nju** [facebook/buck2#917]
First problem, `buildscript_run` handles Cargo environment variables in a roundabout way:

```starlark
buildscript_run(
    name = "ring-0.17.8-build-script-run",
    buildscript_rule = ":ring-0.17.8-build-script-build",
    package_name = "ring",  # internally converts to `CARGO_PKG_NAME`
    env = { ... },
    version = "0.17.8",     # internally converts to `CARGO_PKG_VERSION`
)
```

Instead of directly accepting `CARGO_PKG_NAME` and `CARGO_PKG_VERSION` in the `env` attribute, the rule uses two special attributes, then internally converts them to environment variables, before executing the build script executable.

Second problem, the `cargo_env` settings in fixups don't propagate to `-build-script-run` targets. Some times I have to duplicate environment variables specifically for build scripts:

```toml
cargo_env = true

[[buildscript]]
[buildscript.rustc_flags.env]
CARGO_PKG_VERSION_MAJOR = "XX"
CARGO_PKG_VERSION_MINOR = "XX"
```
